services:
  db:
    image: postgres:15

    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
    ports:
      - "5432:5432"

  dbackend:
    build:
      context: ./dbackend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./dbackend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=blogdb
      - DJANGO_DB_USER=bloguser
      - DJANGO_DB_PASSWORD=blogpass

  vfrontend:
    build:
      context: ./vfrontend
    ports:
      - "8082:8082"
    volumes:
      - ./vfrontend:/app
      - /app/node_modules
    command: npm run serve
    depends_on:
      - dbackend

volumes:
  postgres_data:
